### ISSUE TITLE
Fix Code of Conduct link

### ISSUE THREAD

**Issue by mikeacosta** [Project-Books/project-books.github.io#18]
The link to the Code of Conduct near the top of [this page](https://project-books.github.io/development/contributing/) should be changed to https://project-books.github.io/conduct/code-of-conduct/

Please assign this issue to me.

**Comment by knjk04** [comment]
Hi @mikeacosta, thanks for bringing this up! I'll assign this to you

**Comment by mikeacosta** [comment]
Thanks @knjk04 
[PR](https://github.com/Project-Books/project-books.github.io/pull/19) created.
