### ISSUE TITLE
Fix Link to Core Team Document

### ISSUE THREAD

**Issue by mikeacosta** [Project-Books/project-books.github.io#20]
On the [Becoming a maintainer](https://project-books.github.io/development/maintaining/maintainer/) page, the link for the text "core team document" is broken.  It looks like it should point to https://project-books.github.io/development/maintaining/core-team/

If that is correct, please assign this issue to me.

**Comment by knjk04** [comment]
@mikeacosta Good catch, thanks again! I'll assign this to you
