### ISSUE TITLE
Move Slack icon next to GitHub icon

### ISSUE THREAD

**Issue by knjk04** [Project-Books/project-books.github.io#5]
![image](https://user-images.githubusercontent.com/11173328/117135606-19d92a80-ad9f-11eb-9eba-e8b7145d6395.png)

Move the Slack icon (currently in the footer) to the right of the GitHub icon, as indicated below:

![image](https://user-images.githubusercontent.com/11173328/117135688-35dccc00-ad9f-11eb-83a4-026b7c07eefe.png)

**Comment by kpnigalye** [comment]
I would like to work on this issue. Also please let me know the steps to reproduce the issue. Thank you.

**Comment by knjk04** [comment]
Thanks, I'll assign you!

If you go to https://project-books.github.io/docs/, you can see the problem. To reproduce the problem locally, try running the steps outlined in the README.

**Comment by kpnigalye** [comment]
@knjk04 I have been looking for a solution in official documentation for this but looks like such links can be added only in footer section. I went through the list of clients to see if any of them have done any such customization but couldn't find any. I think as of now, material-mkdocs is not supporting adding additional options in header.

**Comment by knjk04** [comment]
@kpnigalye Thanks for looking into this. I'll close this issue
